apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
  labels:
    app: superset
    app.kubernetes.io/instance: superset
    chart: superset-0.13.4
    heritage: Helm
    release: superset
  name: superset
  namespace: superset
spec:
  ports:
    - name: http
      nodePort: null
      port: !!int "8088"
      protocol: TCP
      targetPort: http
  selector:
    app: superset
    release: superset
  type: LoadBalancer
